### ISSUE TITLE
Problem in Deploying ASCS

### ISSUE THREAD

**Issue by syedkamrannaqvi** [aws-quickstart/quickstart-sap-netweaver-abap#11]
Stack has been failed with this condition

WaitCondition received failed message: 'SAP ASCS install RETRY Failed...ASCS not installed 2nd retry...password error?= ' for uniqueId: i-0458f4f9fdd769427

**Comment by somckitk** [comment]
Hi,

Thanks for reporting the issue. To understand what's going on can you review the /var/log/cfn-init.log and /var/log/cfn-init-cmd.log.

The cfn-init-cmd.log file especially will have the output of the SWPM installation process. You may be able to tell what's going wrong, for example the password you entered may not meet SAP's password requirements.

Thanks.
